name: Cloud Cost Analysis

# on:
#   schedule:
#     - cron: '0 6 * * *'
#   workflow_dispatch:

on:
  push

jobs:
  analyze-costs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r scripts/requirements.txt

      - name: Fetch AWS Costs
        run: python scripts/fetch_aws_costs.py

      - name: Normalize and Store
        run: python scripts/normalize_data.py

      - name: Run Alerts
        run: python scripts/cost_alerts.py